# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Process cores

# Trigger the workflow on push or pull request
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: 3.8

    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
    - name: Build environment information
      run: 'echo "Matrix OS: ${{ matrix.os }} on $HOSTNAME with $(getconf _NPROCESSORS_ONLN) cores"'

    - uses: actions/checkout@v2

    - name: Checkout Kodi repo
      uses: actions/checkout@v2
      with:
        repository: 'garbear/xbmc'
        ref: 'retroplayer-18.8'
        path: game-addons/kodi

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        dpkg -s libasound2-dev || sudo apt-get install -y libasound2-dev # Required by mame
        dpkg -s libpcap-dev || sudo apt-get install -y libpcap-dev # Required by desmume
        dpkg -s mesa-common-dev || sudo apt-get install -y mesa-common-dev # Required by flycast

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Restore game add-on build files
      id: restore-game-addons
      uses: actions/cache@v2
      with:
        path: |
          game-addons
        key: build-game-addons-${{ matrix.os }}-${{ hashFiles('kodi_game_scripting/config.py') }}
        restore-keys: |
          build-game-addons-${{ matrix.os }}-

    - name: Process cores
      env:
        GITHUB_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
      run: |
        ./process_game_addons.py --game-addons-dir="game-addons" --kodi-source-dir="../kodi" --git --compile --push-branch=testing-github-ci --filter="nestopia"
